version: "3.9"
name: 'minecraft-server'
services:
  minecraft-server-1.20.4:
    user: 1000:1003
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 1G
    container_name:  minecraft-server-1.20.4
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: openjdk:21-jdk-bookworm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/samsung980pro250gb/documents/minecraft/server/1.20.4:/app
    ports:
      - "25565:25565"
    working_dir: /app
    command: java -Xmx4G -Xms2G -jar minecraft_server.jar nogui